### ISSUE TITLE
partition.js: Invalid size comparison

### ISSUE THREAD

**Issue by Sanduuz** [PelionIoT/pelion-edge-ready-test-suite#7]
Invalid size comparison in `test-cases/l1_file_system_and_specification_tests/partition.js`

I tried running the Pelion Edge Ready Test Suite and noticed that the file size comparison in the partition.js test case under l1_file_system_and_specification_tests fails with the script thinking 1.8G < 457M.  After some debugging I noticed that the script assumes the sizes to always be in megabytes, yet the script is calling the `df` binary with the `-h` flag. The `-h` flag converts the file sizes from bytes to human readable form (MB, but also GB if the file is big enough). This invalid size comparison can be fixed by using the `-BM` flag instead of the `-h` flag.

Attached is a patch file containing the fix:
[0001-Fix-file-size-comparison.txt](https://github.com/PelionIoT/pelion-edge-ready-test-suite/files/6693975/0001-Fix-file-size-comparison.txt)
 
Feel free to include my fix. I am willing to publish this patch according to the license used in the repository (Apache 2.0).

**Comment by JanneKiiskila** [comment]
This has been fixed to branch release-2.6. Good catch @Sanduuz .

**Comment by JanneKiiskila** [comment]
https://github.com/PelionIoT/pelion-edge-ready-test-suite/releases/tag/v2.6.0
