### ISSUE TITLE
program_and_services.js: Invalid openssl version comparison

### ISSUE THREAD

**Issue by Sanduuz** [PelionIoT/pelion-edge-ready-test-suite#9]
Invalid openssl version comparison in `test-cases/l2_program_tests/program_and_services.js`

I tried running the Pelion Edge Ready Test Suite and noticed that the openssl version comparison in the `program_and_services.js` test case under `l2_program_tests` fails. After some debugging I noticed that the script assumes the version always to end with a "g". However that is not the case. The letter in openssl version indicates updates with bug and security fixes, no new features. This invalid version comparison can be fixed by modifying the command to split by spaces and then taking the second field and removing the letter from the end.

Attached is a patch file containing the fix:
[0003-Fix-openssl-version-comparison.txt](https://github.com/PelionIoT/pelion-edge-ready-test-suite/files/6699089/0003-Fix-openssl-version-comparison.txt)

Feel free to include my fix. I am willing to publish this patch according to the license used in the repository (Apache 2.0).

**Comment by singhbhoopesh** [comment]
Thanks.. Added your patch
